name: Publish to PyPI

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: python3.10 -m venv poetry-venv && ./poetry-venv/bin/pip install poetry
      - name: Build package with poetry
        run: ./poetry-venvbin/poetry build
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
